// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_collection from "./routes/admin/collection.tsx";
import * as $admin_pages from "./routes/admin/pages.tsx";
import * as $admin_requests from "./routes/admin/requests.tsx";
import * as $admin_settings_layout from "./routes/admin/settings/_layout.tsx";
import * as $admin_settings_index from "./routes/admin/settings/index.tsx";
import * as $admin_settings_medias from "./routes/admin/settings/medias.tsx";
import * as $admin_settings_misc from "./routes/admin/settings/misc.tsx";
import * as $admin_settings_styles from "./routes/admin/settings/styles.tsx";
import * as $admin_settings_users from "./routes/admin/settings/users.tsx";
import * as $admin_stats from "./routes/admin/stats.tsx";
import * as $admin_users_id_ from "./routes/admin/users/[id].tsx";
import * as $admin_users_index from "./routes/admin/users/index.tsx";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_index from "./routes/auth/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $AuthForm from "./islands/AuthForm.tsx";
import * as $ConfirmationModal from "./islands/ConfirmationModal.tsx";
import * as $Layout_Navbar from "./islands/Layout/Navbar.tsx";
import * as $Settings_MainSettings from "./islands/Settings/MainSettings.tsx";
import * as $Settings_SettingsChilds_InlineDoubleInput from "./islands/Settings/SettingsChilds/InlineDoubleInput.tsx";
import * as $Settings_SettingsChilds_InlineSingleInput from "./islands/Settings/SettingsChilds/InlineSingleInput.tsx";
import * as $Users_RequestButton from "./islands/Users/RequestButton.tsx";
import * as $Users_RequestSingle from "./islands/Users/RequestSingle.tsx";
import * as $Users_UsersList from "./islands/Users/UsersList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/collection.tsx": $admin_collection,
    "./routes/admin/pages.tsx": $admin_pages,
    "./routes/admin/requests.tsx": $admin_requests,
    "./routes/admin/settings/_layout.tsx": $admin_settings_layout,
    "./routes/admin/settings/index.tsx": $admin_settings_index,
    "./routes/admin/settings/medias.tsx": $admin_settings_medias,
    "./routes/admin/settings/misc.tsx": $admin_settings_misc,
    "./routes/admin/settings/styles.tsx": $admin_settings_styles,
    "./routes/admin/settings/users.tsx": $admin_settings_users,
    "./routes/admin/stats.tsx": $admin_stats,
    "./routes/admin/users/[id].tsx": $admin_users_id_,
    "./routes/admin/users/index.tsx": $admin_users_index,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/index.tsx": $auth_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AuthForm.tsx": $AuthForm,
    "./islands/ConfirmationModal.tsx": $ConfirmationModal,
    "./islands/Layout/Navbar.tsx": $Layout_Navbar,
    "./islands/Settings/MainSettings.tsx": $Settings_MainSettings,
    "./islands/Settings/SettingsChilds/InlineDoubleInput.tsx":
      $Settings_SettingsChilds_InlineDoubleInput,
    "./islands/Settings/SettingsChilds/InlineSingleInput.tsx":
      $Settings_SettingsChilds_InlineSingleInput,
    "./islands/Users/RequestButton.tsx": $Users_RequestButton,
    "./islands/Users/RequestSingle.tsx": $Users_RequestSingle,
    "./islands/Users/UsersList.tsx": $Users_UsersList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
