// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_collection from "./routes/admin/collection.tsx";
import * as $admin_pages from "./routes/admin/pages.tsx";
import * as $admin_requests from "./routes/admin/requests.tsx";
import * as $admin_settings_layout from "./routes/admin/settings/_layout.tsx";
import * as $admin_settings_index from "./routes/admin/settings/index.tsx";
import * as $admin_settings_medias from "./routes/admin/settings/medias.tsx";
import * as $admin_settings_misc from "./routes/admin/settings/misc.tsx";
import * as $admin_settings_styles from "./routes/admin/settings/styles.tsx";
import * as $admin_settings_users from "./routes/admin/settings/users.tsx";
import * as $admin_stats from "./routes/admin/stats.tsx";
import * as $admin_users_id_ from "./routes/admin/users/[id].tsx";
import * as $admin_users_index from "./routes/admin/users/index.tsx";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_index from "./routes/auth/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $AuthForm from "./islands/AuthForm.tsx";
import * as $ConfirmationModal from "./islands/ConfirmationModal.tsx";
import * as $Layout_Navbar from "./islands/Layout/Navbar.tsx";
import * as $Layout_NavbarItem from "./islands/Layout/NavbarItem.tsx";
import * as $Settings_Main_APIInput from "./islands/Settings/Main/APIInput.tsx";
import * as $Settings_Main_EmailMatrix from "./islands/Settings/Main/EmailMatrix.tsx";
import * as $Settings_Main_Index from "./islands/Settings/Main/Index.tsx";
import * as $Settings_Main_MiscInput from "./islands/Settings/Main/MiscInput.tsx";
import * as $Settings_MainInputs from "./islands/Settings/MainInputs.tsx";
import * as $Settings_Users_RequestButton from "./islands/Settings/Users/RequestButton.tsx";
import * as $Settings_Users_RequestSingle from "./islands/Settings/Users/RequestSingle.tsx";
import * as $Settings_Users_UsersList from "./islands/Settings/Users/UsersList.tsx";
import * as $Settings_Users_UsersList_UserActions from "./islands/Settings/Users/UsersList/UserActions.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/collection.tsx": $admin_collection,
    "./routes/admin/pages.tsx": $admin_pages,
    "./routes/admin/requests.tsx": $admin_requests,
    "./routes/admin/settings/_layout.tsx": $admin_settings_layout,
    "./routes/admin/settings/index.tsx": $admin_settings_index,
    "./routes/admin/settings/medias.tsx": $admin_settings_medias,
    "./routes/admin/settings/misc.tsx": $admin_settings_misc,
    "./routes/admin/settings/styles.tsx": $admin_settings_styles,
    "./routes/admin/settings/users.tsx": $admin_settings_users,
    "./routes/admin/stats.tsx": $admin_stats,
    "./routes/admin/users/[id].tsx": $admin_users_id_,
    "./routes/admin/users/index.tsx": $admin_users_index,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/index.tsx": $auth_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AuthForm.tsx": $AuthForm,
    "./islands/ConfirmationModal.tsx": $ConfirmationModal,
    "./islands/Layout/Navbar.tsx": $Layout_Navbar,
    "./islands/Layout/NavbarItem.tsx": $Layout_NavbarItem,
    "./islands/Settings/Main/APIInput.tsx": $Settings_Main_APIInput,
    "./islands/Settings/Main/EmailMatrix.tsx": $Settings_Main_EmailMatrix,
    "./islands/Settings/Main/Index.tsx": $Settings_Main_Index,
    "./islands/Settings/Main/MiscInput.tsx": $Settings_Main_MiscInput,
    "./islands/Settings/MainInputs.tsx": $Settings_MainInputs,
    "./islands/Settings/Users/RequestButton.tsx": $Settings_Users_RequestButton,
    "./islands/Settings/Users/RequestSingle.tsx": $Settings_Users_RequestSingle,
    "./islands/Settings/Users/UsersList.tsx": $Settings_Users_UsersList,
    "./islands/Settings/Users/UsersList/UserActions.tsx":
      $Settings_Users_UsersList_UserActions,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
