CREATE TABLE "Content" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "content" integer,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Brickable" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" integer NOT NULL
);

CREATE TABLE "Brick_Main" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "title" varchar(255),
  "text" varchar(1000),
  "media" integer NOT NULL,
  "url" varchar(2083),
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Brick_Single" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "title" varchar(255),
  "media" integer NOT NULL,
  "link" integer UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Brick_Album" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "title" varchar(255),
  "media" integer NOT NULL,
  "link" integer UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Brick_Text" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "text" text,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Brick_Socials" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "plateform" integer UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Brick_Tile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "bricks" integer UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Tracklist" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "track" integer UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Track" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "artist" integer UNIQUE,
  "link" integer UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Artist" (
  "id" integer PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "url" varchar(2083),
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "media_type" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "url" varchar(2083) DEFAULT 'https://placehold.co/600x400',
  "adjustement" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Video" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "url" varchar(2083) DEFAULT 'https://placehold.co/600x400',
  "autoplay" boolean DEFAULT false,
  "adjustement" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Audio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "url" varchar(2083) DEFAULT 'https://placehold.co/600x400',
  "autodetect_source" boolean DEFAULT true,
  "media_cover" integer NOT NULL,
  "type" integer NOT NULL,
  "controls" int DEFAULT 1,
  "cta" int,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Media_Adjustement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Audio_Type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Audio_Controls" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "play" boolean DEFAULT true,
  "progress" boolean DEFAULT true,
  "duration" boolean DEFAULT true,
  "volume" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Audio_Link" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar(100) NOT NULL,
  "url" varchar(2083) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Plateform" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "image" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Plateform_Link" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plateform" integer,
  "url" varchar(2083) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "blocked" boolean DEFAULT true,
  "role" integer NOT NULL,
  "content_created" integer UNIQUE,
  "created_by" integer NOT NULL,
  "accepted_by" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "Users_Roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "label" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Website_Settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email_contact" integer NOT NULL,
  "email_user_creator" integer NOT NULL,
  "email_logging" integer NOT NULL,
  "email_administrator" integer NOT NULL,
  "email_default_sender" varchar(255) NOT NULL,
  "api_spotify" varchar(510),
  "api_deezer" varchar(510),
  "api_soundcloud" varchar(510),
  "api_amazon_music" varchar(510),
  "api_youtube_music" varchar(510),
  "api_tidal" varchar(510),
  "website_url" varchar(2083) NOT NULL,
  "website_title" varchar(255),
  "website_icone" integer,
  "website_keywords" varchar(510),
  "website_language" integer NOT NULL,
  "media_max_size_mb" integer,
  "media_max_size_height" integer,
  "media_auto_optimize" boolean DEFAULT true,
  "media_lazyload" boolean DEFAULT true,
  "style_color_auto" boolean DEFAULT false,
  "style_color_main" varchar(8),
  "style_color_secondary" varchar(8),
  "style_theme_toggle" boolean DEFAULT false,
  "style_font_main" varchar(100),
  "style_font_secondary" varchar(100),
  "misc_confidentiality" varchar(2083),
  "created_at" timestamp DEFAULT (now()),
  "created_by" integer DEFAULT 0,
  "modified_at" timestamp,
  "hidden" boolean DEFAULT false
);

CREATE TABLE "Available_Languages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Mail_Pairing" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email_recipient" varchar(255) NOT NULL,
  "email_sender" varchar(255) NOT NULL
);

COMMENT ON COLUMN "Audio_Controls"."id" IS 'define the first of this controls to default value';

COMMENT ON COLUMN "Website_Settings"."media_max_size_mb" IS 'Should be between 0 and 10000';

COMMENT ON COLUMN "Website_Settings"."style_color_main" IS 'should be hex color with alpha';

COMMENT ON COLUMN "Website_Settings"."style_color_secondary" IS 'should be hex color with alpha';

ALTER TABLE "Content" ADD FOREIGN KEY ("content") REFERENCES "Brickable" ("id");

ALTER TABLE "Content" ADD FOREIGN KEY ("content") REFERENCES "Media" ("id");

ALTER TABLE "Content" ADD FOREIGN KEY ("content") REFERENCES "Plateform" ("id");

ALTER TABLE "Content" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Brickable" ADD FOREIGN KEY ("content") REFERENCES "Brick_Main" ("id");

ALTER TABLE "Brickable" ADD FOREIGN KEY ("content") REFERENCES "Brick_Single" ("id");

ALTER TABLE "Brickable" ADD FOREIGN KEY ("content") REFERENCES "Brick_Album" ("id");

ALTER TABLE "Brickable" ADD FOREIGN KEY ("content") REFERENCES "Brick_Tile" ("id");

ALTER TABLE "Brickable" ADD FOREIGN KEY ("content") REFERENCES "Brick_Text" ("id");

ALTER TABLE "Brickable" ADD FOREIGN KEY ("content") REFERENCES "Brick_Socials" ("id");

ALTER TABLE "Brick_Main" ADD FOREIGN KEY ("media") REFERENCES "Image" ("id");

ALTER TABLE "Brick_Main" ADD FOREIGN KEY ("media") REFERENCES "Video" ("id");

ALTER TABLE "Brick_Main" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Brick_Single" ADD FOREIGN KEY ("media") REFERENCES "Image" ("id");

ALTER TABLE "Brick_Single" ADD FOREIGN KEY ("media") REFERENCES "Video" ("id");

CREATE TABLE "Plateform_Link_Brick_Single" (
  "Plateform_Link_id" integer,
  "Brick_Single_link" integer,
  PRIMARY KEY ("Plateform_Link_id", "Brick_Single_link")
);

ALTER TABLE "Plateform_Link_Brick_Single" ADD FOREIGN KEY ("Plateform_Link_id") REFERENCES "Plateform_Link" ("id");

ALTER TABLE "Plateform_Link_Brick_Single" ADD FOREIGN KEY ("Brick_Single_link") REFERENCES "Brick_Single" ("link");


ALTER TABLE "Brick_Single" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Brick_Album" ADD FOREIGN KEY ("media") REFERENCES "Image" ("id");

ALTER TABLE "Brick_Album" ADD FOREIGN KEY ("media") REFERENCES "Video" ("id");

CREATE TABLE "Plateform_Link_Brick_Album" (
  "Plateform_Link_id" integer,
  "Brick_Album_link" integer,
  PRIMARY KEY ("Plateform_Link_id", "Brick_Album_link")
);

ALTER TABLE "Plateform_Link_Brick_Album" ADD FOREIGN KEY ("Plateform_Link_id") REFERENCES "Plateform_Link" ("id");

ALTER TABLE "Plateform_Link_Brick_Album" ADD FOREIGN KEY ("Brick_Album_link") REFERENCES "Brick_Album" ("link");


ALTER TABLE "Brick_Album" ADD FOREIGN KEY ("link") REFERENCES "Tracklist" ("id");

ALTER TABLE "Brick_Album" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Brick_Text" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

CREATE TABLE "Plateform_Link_Brick_Socials" (
  "Plateform_Link_id" integer,
  "Brick_Socials_plateform" integer,
  PRIMARY KEY ("Plateform_Link_id", "Brick_Socials_plateform")
);

ALTER TABLE "Plateform_Link_Brick_Socials" ADD FOREIGN KEY ("Plateform_Link_id") REFERENCES "Plateform_Link" ("id");

ALTER TABLE "Plateform_Link_Brick_Socials" ADD FOREIGN KEY ("Brick_Socials_plateform") REFERENCES "Brick_Socials" ("plateform");


ALTER TABLE "Brick_Socials" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

CREATE TABLE "Brick_Single_Brick_Tile" (
  "Brick_Single_id" integer,
  "Brick_Tile_bricks" integer,
  PRIMARY KEY ("Brick_Single_id", "Brick_Tile_bricks")
);

ALTER TABLE "Brick_Single_Brick_Tile" ADD FOREIGN KEY ("Brick_Single_id") REFERENCES "Brick_Single" ("id");

ALTER TABLE "Brick_Single_Brick_Tile" ADD FOREIGN KEY ("Brick_Tile_bricks") REFERENCES "Brick_Tile" ("bricks");


CREATE TABLE "Brick_Album_Brick_Tile" (
  "Brick_Album_id" integer,
  "Brick_Tile_bricks" integer,
  PRIMARY KEY ("Brick_Album_id", "Brick_Tile_bricks")
);

ALTER TABLE "Brick_Album_Brick_Tile" ADD FOREIGN KEY ("Brick_Album_id") REFERENCES "Brick_Album" ("id");

ALTER TABLE "Brick_Album_Brick_Tile" ADD FOREIGN KEY ("Brick_Tile_bricks") REFERENCES "Brick_Tile" ("bricks");


CREATE TABLE "Media_Brick_Tile" (
  "Media_id" integer,
  "Brick_Tile_bricks" integer,
  PRIMARY KEY ("Media_id", "Brick_Tile_bricks")
);

ALTER TABLE "Media_Brick_Tile" ADD FOREIGN KEY ("Media_id") REFERENCES "Media" ("id");

ALTER TABLE "Media_Brick_Tile" ADD FOREIGN KEY ("Brick_Tile_bricks") REFERENCES "Brick_Tile" ("bricks");


CREATE TABLE "Brick_Text_Brick_Tile" (
  "Brick_Text_id" integer,
  "Brick_Tile_bricks" integer,
  PRIMARY KEY ("Brick_Text_id", "Brick_Tile_bricks")
);

ALTER TABLE "Brick_Text_Brick_Tile" ADD FOREIGN KEY ("Brick_Text_id") REFERENCES "Brick_Text" ("id");

ALTER TABLE "Brick_Text_Brick_Tile" ADD FOREIGN KEY ("Brick_Tile_bricks") REFERENCES "Brick_Tile" ("bricks");


CREATE TABLE "Brick_Socials_Brick_Tile" (
  "Brick_Socials_id" integer,
  "Brick_Tile_bricks" integer,
  PRIMARY KEY ("Brick_Socials_id", "Brick_Tile_bricks")
);

ALTER TABLE "Brick_Socials_Brick_Tile" ADD FOREIGN KEY ("Brick_Socials_id") REFERENCES "Brick_Socials" ("id");

ALTER TABLE "Brick_Socials_Brick_Tile" ADD FOREIGN KEY ("Brick_Tile_bricks") REFERENCES "Brick_Tile" ("bricks");


ALTER TABLE "Brick_Tile" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

CREATE TABLE "Track_Tracklist" (
  "Track_id" integer,
  "Tracklist_track" integer,
  PRIMARY KEY ("Track_id", "Tracklist_track")
);

ALTER TABLE "Track_Tracklist" ADD FOREIGN KEY ("Track_id") REFERENCES "Track" ("id");

ALTER TABLE "Track_Tracklist" ADD FOREIGN KEY ("Tracklist_track") REFERENCES "Tracklist" ("track");


ALTER TABLE "Tracklist" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

CREATE TABLE "Artist_Track" (
  "Artist_id" integer,
  "Track_artist" integer,
  PRIMARY KEY ("Artist_id", "Track_artist")
);

ALTER TABLE "Artist_Track" ADD FOREIGN KEY ("Artist_id") REFERENCES "Artist" ("id");

ALTER TABLE "Artist_Track" ADD FOREIGN KEY ("Track_artist") REFERENCES "Track" ("artist");


CREATE TABLE "Plateform_Link_Track" (
  "Plateform_Link_id" integer,
  "Track_link" integer,
  PRIMARY KEY ("Plateform_Link_id", "Track_link")
);

ALTER TABLE "Plateform_Link_Track" ADD FOREIGN KEY ("Plateform_Link_id") REFERENCES "Plateform_Link" ("id");

ALTER TABLE "Plateform_Link_Track" ADD FOREIGN KEY ("Track_link") REFERENCES "Track" ("link");


ALTER TABLE "Track" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Artist" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Media" ADD FOREIGN KEY ("media_type") REFERENCES "Image" ("id");

ALTER TABLE "Media" ADD FOREIGN KEY ("media_type") REFERENCES "Video" ("id");

ALTER TABLE "Media" ADD FOREIGN KEY ("media_type") REFERENCES "Audio" ("id");

ALTER TABLE "Media" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Image" ADD FOREIGN KEY ("adjustement") REFERENCES "Media_Adjustement" ("id");

ALTER TABLE "Image" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Video" ADD FOREIGN KEY ("adjustement") REFERENCES "Media_Adjustement" ("id");

ALTER TABLE "Video" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Audio" ADD FOREIGN KEY ("media_cover") REFERENCES "Image" ("id");

ALTER TABLE "Audio" ADD FOREIGN KEY ("media_cover") REFERENCES "Video" ("id");

ALTER TABLE "Audio" ADD FOREIGN KEY ("type") REFERENCES "Audio_Type" ("id");

ALTER TABLE "Audio" ADD FOREIGN KEY ("controls") REFERENCES "Audio_Controls" ("id");

ALTER TABLE "Audio" ADD FOREIGN KEY ("cta") REFERENCES "Audio_Link" ("id");

ALTER TABLE "Audio" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Audio_Controls" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Audio_Link" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Plateform" ADD FOREIGN KEY ("image") REFERENCES "Image" ("id");

ALTER TABLE "Plateform" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Plateform_Link" ADD FOREIGN KEY ("plateform") REFERENCES "Plateform" ("id");

ALTER TABLE "Plateform_Link" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("role") REFERENCES "Users_Roles" ("id");

CREATE TABLE "Content_Users" (
  "Content_id" integer,
  "Users_content_created" integer,
  PRIMARY KEY ("Content_id", "Users_content_created")
);

ALTER TABLE "Content_Users" ADD FOREIGN KEY ("Content_id") REFERENCES "Content" ("id");

ALTER TABLE "Content_Users" ADD FOREIGN KEY ("Users_content_created") REFERENCES "Users" ("content_created");


ALTER TABLE "Users" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("accepted_by") REFERENCES "Users" ("id");

ALTER TABLE "Users_Roles" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("email_contact") REFERENCES "Mail_Pairing" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("email_user_creator") REFERENCES "Mail_Pairing" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("email_logging") REFERENCES "Mail_Pairing" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("email_administrator") REFERENCES "Mail_Pairing" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("website_icone") REFERENCES "Media" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("website_language") REFERENCES "Available_Languages" ("id");

ALTER TABLE "Website_Settings" ADD FOREIGN KEY ("created_by") REFERENCES "Users" ("id");
