

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."brick_type" AS ENUM (
    'HeroSection',
    'Single',
    'Album',
    'Text',
    'Platform_Link'
);


ALTER TYPE "public"."brick_type" OWNER TO "postgres";


COMMENT ON TYPE "public"."brick_type" IS 'Types of the bricks. Table names.';



CREATE TYPE "public"."herosection_style" AS ENUM (
    'scrolling-hero'
);


ALTER TYPE "public"."herosection_style" OWNER TO "postgres";


COMMENT ON TYPE "public"."herosection_style" IS 'Variants of the HeroSection';



CREATE TYPE "public"."media_fit" AS ENUM (
    'best',
    'cover',
    'contain'
);


ALTER TYPE "public"."media_fit" OWNER TO "postgres";


COMMENT ON TYPE "public"."media_fit" IS 'Object fit of the medias';



CREATE TYPE "public"."media_type" AS ENUM (
    'Audios',
    'Videos',
    'Images',
    'Misc'
);


ALTER TYPE "public"."media_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_user_id_by_email"("email" "text") RETURNS TABLE("id" "uuid")
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $_$
BEGIN
  RETURN QUERY SELECT au.id FROM auth.users au WHERE au.email = $1;
END;
$_$;


ALTER FUNCTION "public"."get_user_id_by_email"("email" "text") OWNER TO "postgres";


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Artist" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "name" character varying,
    "url" character varying
);


ALTER TABLE "public"."Artist" OWNER TO "postgres";


COMMENT ON TABLE "public"."Artist" IS 'This is a duplicate of base_brick';



CREATE TABLE IF NOT EXISTS "public"."Medias_Controls" (
    "id" integer NOT NULL,
    "play" boolean DEFAULT true,
    "progress" boolean DEFAULT true,
    "duration" boolean DEFAULT true,
    "volume" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "hidden" boolean DEFAULT false,
    "name" "text" DEFAULT ''::"text"
);


ALTER TABLE "public"."Medias_Controls" OWNER TO "postgres";


COMMENT ON COLUMN "public"."Medias_Controls"."id" IS 'define the first of this controls to default value';



ALTER TABLE "public"."Medias_Controls" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Audio_Controls_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."CTA_Link" (
    "id" integer NOT NULL,
    "label" character varying(100) DEFAULT ''::character varying NOT NULL,
    "url" character varying(2083) DEFAULT ''::character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "hidden" boolean DEFAULT false
);


ALTER TABLE "public"."CTA_Link" OWNER TO "postgres";


ALTER TABLE "public"."CTA_Link" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Audio_Link_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Available_Languages" (
    "id" integer NOT NULL,
    "name" character varying(100) NOT NULL
);


ALTER TABLE "public"."Available_Languages" OWNER TO "postgres";


ALTER TABLE "public"."Available_Languages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Available_Languages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Bricks_Album" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "title" character varying,
    "media" "uuid",
    "cta" integer,
    "hoverable" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Bricks_Album" OWNER TO "postgres";


COMMENT ON TABLE "public"."Bricks_Album" IS 'This is a duplicate of Bricks_Single';



CREATE TABLE IF NOT EXISTS "public"."Bricks_Album_Platform_Link" (
    "Album" bigint NOT NULL,
    "Platform_Link" bigint NOT NULL
);


ALTER TABLE "public"."Bricks_Album_Platform_Link" OWNER TO "postgres";


COMMENT ON TABLE "public"."Bricks_Album_Platform_Link" IS 'This is a duplicate of Bricks_Single_Platform_Link';



CREATE TABLE IF NOT EXISTS "public"."Bricks_Album_Track" (
    "Album" bigint NOT NULL,
    "Track" bigint NOT NULL
);


ALTER TABLE "public"."Bricks_Album_Track" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Bricks_HeroSection" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "title" character varying,
    "subtitle" character varying,
    "media" "uuid",
    "cta" integer,
    "style" "public"."herosection_style" DEFAULT 'scrolling-hero'::"public"."herosection_style" NOT NULL
);


ALTER TABLE "public"."Bricks_HeroSection" OWNER TO "postgres";


ALTER TABLE "public"."Bricks_HeroSection" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bricks_HeroSection_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Bricks_Single" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "title" character varying,
    "media" "uuid",
    "cta" integer,
    "hoverable" boolean DEFAULT false NOT NULL,
    "track" bigint
);


ALTER TABLE "public"."Bricks_Single" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Bricks_Single_Platform_Link" (
    "Single" bigint NOT NULL,
    "Platform_Link" bigint NOT NULL
);


ALTER TABLE "public"."Bricks_Single_Platform_Link" OWNER TO "postgres";


ALTER TABLE "public"."Bricks_Album" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bricks_Single_duplicate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Bricks_Text" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "text" "text",
    "media" "uuid"
);


ALTER TABLE "public"."Bricks_Text" OWNER TO "postgres";


COMMENT ON TABLE "public"."Bricks_Text" IS 'Text brick';



ALTER TABLE "public"."Bricks_Text" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bricks_Single_duplicate_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Bricks_Single" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bricks_Single_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Mail_Pairing" (
    "id" integer NOT NULL,
    "email_recipient" character varying(255) NOT NULL,
    "email_sender" character varying(255) NOT NULL
);


ALTER TABLE "public"."Mail_Pairing" OWNER TO "postgres";


ALTER TABLE "public"."Mail_Pairing" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Mail_Pairing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Media_Adjustement" (
    "id" integer NOT NULL,
    "name" character varying(100) NOT NULL
);


ALTER TABLE "public"."Media_Adjustement" OWNER TO "postgres";


ALTER TABLE "public"."Media_Adjustement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Media_Adjustement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Medias" (
    "id" "uuid" NOT NULL,
    "name" character varying NOT NULL,
    "display_name" character varying NOT NULL,
    "public_src" character varying DEFAULT ''::character varying,
    "alt" "text" DEFAULT ''::"text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "autoplay" boolean DEFAULT false,
    "autodetect_source" boolean DEFAULT true,
    "cover" "uuid",
    "controls" integer DEFAULT 1,
    "cta" integer DEFAULT 1,
    "type" "public"."media_type",
    "filesize" bigint,
    "extension" "text",
    "object_fit" "public"."media_fit" DEFAULT 'best'::"public"."media_fit"
);


ALTER TABLE "public"."Medias" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Node" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "x" numeric NOT NULL,
    "y" numeric NOT NULL,
    "width" numeric NOT NULL,
    "height" numeric NOT NULL,
    "locked" boolean DEFAULT false NOT NULL,
    "type" "public"."brick_type",
    "HeroSection" bigint,
    "Single" bigint,
    "Album" bigint,
    "Text" bigint,
    "Platform_Link" bigint
);


ALTER TABLE "public"."Node" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Platform" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "name" character varying NOT NULL,
    "icon" character varying
);


ALTER TABLE "public"."Platform" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Platform_Link" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "name" character varying NOT NULL,
    "url" character varying,
    "platform" bigint,
    "in_footer" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Platform_Link" OWNER TO "postgres";


COMMENT ON COLUMN "public"."Platform_Link"."in_footer" IS 'is this link displayed in the app footer';



ALTER TABLE "public"."Platform" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Platform_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Settings" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user" "uuid",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "main" "jsonb",
    "medias" "jsonb",
    "styles" "jsonb",
    "misc" "jsonb"
);


ALTER TABLE "public"."Settings" OWNER TO "postgres";


ALTER TABLE "public"."Settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Track" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."Track" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Track_Artist" (
    "tracklist" bigint NOT NULL,
    "artist" bigint NOT NULL
);


ALTER TABLE "public"."Track_Artist" OWNER TO "postgres";


COMMENT ON TABLE "public"."Track_Artist" IS 'This is a duplicate of Track_Platform_Link';



CREATE TABLE IF NOT EXISTS "public"."Track_Platform_Link" (
    "tracklist" bigint NOT NULL,
    "platforms" bigint NOT NULL
);


ALTER TABLE "public"."Track_Platform_Link" OWNER TO "postgres";


COMMENT ON TABLE "public"."Track_Platform_Link" IS 'This is a duplicate of Bricks_Single_Platform_Link';






CREATE TABLE IF NOT EXISTS "public"."base_brick" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."base_brick" OWNER TO "postgres";


ALTER TABLE "public"."Platform_Link" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."base_brick_duplicate_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Artist" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."base_brick_duplicate_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Track" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."base_brick_duplicate_id_seq2"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."base_brick" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."base_brick_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Medias_Controls"
    ADD CONSTRAINT "Audio_Controls_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CTA_Link"
    ADD CONSTRAINT "Audio_Link_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Available_Languages"
    ADD CONSTRAINT "Available_Languages_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Available_Languages"
    ADD CONSTRAINT "Available_Languages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Bricks_Single_Platform_Link"
    ADD CONSTRAINT "Brick_Single_Platform_Link_pkey" PRIMARY KEY ("Single", "Platform_Link");



ALTER TABLE ONLY "public"."Bricks_Album_Platform_Link"
    ADD CONSTRAINT "Bricks_Album_Platform_Link_pkey" PRIMARY KEY ("Album", "Platform_Link");



ALTER TABLE ONLY "public"."Bricks_Album_Track"
    ADD CONSTRAINT "Bricks_Album_Track_pkey" PRIMARY KEY ("Album", "Track");



ALTER TABLE ONLY "public"."Bricks_HeroSection"
    ADD CONSTRAINT "Bricks_HeroSection_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Bricks_HeroSection"
    ADD CONSTRAINT "Bricks_HeroSection_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Bricks_Album"
    ADD CONSTRAINT "Bricks_Single_duplicate_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Bricks_Text"
    ADD CONSTRAINT "Bricks_Single_duplicate_name_key1" UNIQUE ("name");



ALTER TABLE ONLY "public"."Bricks_Album"
    ADD CONSTRAINT "Bricks_Single_duplicate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Bricks_Text"
    ADD CONSTRAINT "Bricks_Single_duplicate_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Bricks_Single"
    ADD CONSTRAINT "Bricks_Single_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Bricks_Single"
    ADD CONSTRAINT "Bricks_Single_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Mail_Pairing"
    ADD CONSTRAINT "Mail_Pairing_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Media_Adjustement"
    ADD CONSTRAINT "Media_Adjustement_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Media_Adjustement"
    ADD CONSTRAINT "Media_Adjustement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Node"
    ADD CONSTRAINT "Nodes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Platform"
    ADD CONSTRAINT "Platform_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Platform"
    ADD CONSTRAINT "Platform_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Settings"
    ADD CONSTRAINT "Settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Track_Artist"
    ADD CONSTRAINT "Track_Artist_pkey" PRIMARY KEY ("tracklist", "artist");



ALTER TABLE ONLY "public"."Track_Platform_Link"
    ADD CONSTRAINT "Track_Platform_Link_pkey" PRIMARY KEY ("tracklist", "platforms");






ALTER TABLE ONLY "public"."Platform_Link"
    ADD CONSTRAINT "base_brick_duplicate_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Track"
    ADD CONSTRAINT "base_brick_duplicate_name_key1" UNIQUE ("name");



ALTER TABLE ONLY "public"."Platform_Link"
    ADD CONSTRAINT "base_brick_duplicate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Artist"
    ADD CONSTRAINT "base_brick_duplicate_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Track"
    ADD CONSTRAINT "base_brick_duplicate_pkey2" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."base_brick"
    ADD CONSTRAINT "base_brick_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."base_brick"
    ADD CONSTRAINT "base_brick_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Medias"
    ADD CONSTRAINT "medias_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Medias"
    ADD CONSTRAINT "medias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Bricks_Album_Platform_Link"
    ADD CONSTRAINT "Bricks_Album_Platform_Link_Album_fkey" FOREIGN KEY ("Album") REFERENCES "public"."Bricks_Album"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bricks_Album_Platform_Link"
    ADD CONSTRAINT "Bricks_Album_Platform_Link_Platform_Link_fkey" FOREIGN KEY ("Platform_Link") REFERENCES "public"."Platform_Link"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bricks_Album_Track"
    ADD CONSTRAINT "Bricks_Album_Track_Album_fkey" FOREIGN KEY ("Album") REFERENCES "public"."Bricks_Album"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bricks_Album_Track"
    ADD CONSTRAINT "Bricks_Album_Track_Track_fkey" FOREIGN KEY ("Track") REFERENCES "public"."Track"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bricks_HeroSection"
    ADD CONSTRAINT "Bricks_HeroSection_cta_fkey" FOREIGN KEY ("cta") REFERENCES "public"."CTA_Link"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_HeroSection"
    ADD CONSTRAINT "Bricks_HeroSection_media_fkey" FOREIGN KEY ("media") REFERENCES "public"."Medias"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_Single_Platform_Link"
    ADD CONSTRAINT "Bricks_Single_Platform_Link_Platform_Link_fkey" FOREIGN KEY ("Platform_Link") REFERENCES "public"."Platform_Link"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bricks_Single_Platform_Link"
    ADD CONSTRAINT "Bricks_Single_Platform_Link_Single_fkey" FOREIGN KEY ("Single") REFERENCES "public"."Bricks_Single"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bricks_Single"
    ADD CONSTRAINT "Bricks_Single_cta_fkey" FOREIGN KEY ("cta") REFERENCES "public"."CTA_Link"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_Album"
    ADD CONSTRAINT "Bricks_Single_duplicate_cta_fkey" FOREIGN KEY ("cta") REFERENCES "public"."CTA_Link"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_Album"
    ADD CONSTRAINT "Bricks_Single_duplicate_media_fkey" FOREIGN KEY ("media") REFERENCES "public"."Medias"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_Single"
    ADD CONSTRAINT "Bricks_Single_media_fkey" FOREIGN KEY ("media") REFERENCES "public"."Medias"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_Single"
    ADD CONSTRAINT "Bricks_Single_track_fkey" FOREIGN KEY ("track") REFERENCES "public"."Track"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Bricks_Text"
    ADD CONSTRAINT "Bricks_Text_media_fkey" FOREIGN KEY ("media") REFERENCES "public"."Medias"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Node"
    ADD CONSTRAINT "Node_Album_fkey" FOREIGN KEY ("Album") REFERENCES "public"."Bricks_Album"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Node"
    ADD CONSTRAINT "Node_HeroSection_fkey" FOREIGN KEY ("HeroSection") REFERENCES "public"."Bricks_HeroSection"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Node"
    ADD CONSTRAINT "Node_Platform_Link_fkey" FOREIGN KEY ("Platform_Link") REFERENCES "public"."Platform_Link"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Node"
    ADD CONSTRAINT "Node_Single_fkey" FOREIGN KEY ("Single") REFERENCES "public"."Bricks_Single"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Node"
    ADD CONSTRAINT "Node_Text_fkey" FOREIGN KEY ("Text") REFERENCES "public"."Bricks_Text"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Platform_Link"
    ADD CONSTRAINT "Platform_Link_platform_fkey" FOREIGN KEY ("platform") REFERENCES "public"."Platform"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Settings"
    ADD CONSTRAINT "Settings_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Track_Artist"
    ADD CONSTRAINT "Track_Artist_artist_fkey" FOREIGN KEY ("artist") REFERENCES "public"."Artist"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Track_Artist"
    ADD CONSTRAINT "Track_Artist_tracklist_fkey" FOREIGN KEY ("tracklist") REFERENCES "public"."Track"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Track_Platform_Link"
    ADD CONSTRAINT "Track_Platform_Link_platforms_fkey" FOREIGN KEY ("platforms") REFERENCES "public"."Platform_Link"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Track_Platform_Link"
    ADD CONSTRAINT "Track_Platform_Link_tracklist_fkey" FOREIGN KEY ("tracklist") REFERENCES "public"."Track"("id") ON UPDATE CASCADE ON DELETE CASCADE;





ALTER TABLE ONLY "public"."Medias"
    ADD CONSTRAINT "medias_controls_fkey" FOREIGN KEY ("controls") REFERENCES "public"."Medias_Controls"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Medias"
    ADD CONSTRAINT "medias_cover_fkey" FOREIGN KEY ("cover") REFERENCES "public"."Medias"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Medias"
    ADD CONSTRAINT "medias_cta_fkey" FOREIGN KEY ("cta") REFERENCES "public"."CTA_Link"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE "public"."Artist" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_Album" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_Album_Platform_Link" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_Album_Track" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_HeroSection" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_Single" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_Single_Platform_Link" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bricks_Text" ENABLE ROW LEVEL SECURITY;



ALTER TABLE "public"."Platform" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Platform_Link" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Track" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Track_Artist" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Track_Platform_Link" ENABLE ROW LEVEL SECURITY;



ALTER TABLE "public"."base_brick" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";




GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
































































































































































































GRANT ALL ON FUNCTION "public"."get_user_id_by_email"("email" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_id_by_email"("email" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_id_by_email"("email" "text") TO "service_role";























GRANT ALL ON TABLE "public"."Artist" TO "anon";
GRANT ALL ON TABLE "public"."Artist" TO "authenticated";
GRANT ALL ON TABLE "public"."Artist" TO "service_role";



GRANT ALL ON TABLE "public"."Medias_Controls" TO "anon";
GRANT ALL ON TABLE "public"."Medias_Controls" TO "authenticated";
GRANT ALL ON TABLE "public"."Medias_Controls" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Audio_Controls_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Audio_Controls_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Audio_Controls_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."CTA_Link" TO "anon";
GRANT ALL ON TABLE "public"."CTA_Link" TO "authenticated";
GRANT ALL ON TABLE "public"."CTA_Link" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Audio_Link_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Audio_Link_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Audio_Link_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Available_Languages" TO "anon";
GRANT ALL ON TABLE "public"."Available_Languages" TO "authenticated";
GRANT ALL ON TABLE "public"."Available_Languages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Available_Languages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Available_Languages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Available_Languages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_Album" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_Album" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_Album" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_Album_Platform_Link" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_Album_Platform_Link" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_Album_Platform_Link" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_Album_Track" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_Album_Track" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_Album_Track" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_HeroSection" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_HeroSection" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_HeroSection" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Bricks_HeroSection_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bricks_HeroSection_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bricks_HeroSection_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_Single" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_Single" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_Single" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_Single_Platform_Link" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_Single_Platform_Link" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_Single_Platform_Link" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Bricks_Single_duplicate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bricks_Single_duplicate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bricks_Single_duplicate_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Bricks_Text" TO "anon";
GRANT ALL ON TABLE "public"."Bricks_Text" TO "authenticated";
GRANT ALL ON TABLE "public"."Bricks_Text" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Bricks_Single_duplicate_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bricks_Single_duplicate_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bricks_Single_duplicate_id_seq1" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Bricks_Single_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bricks_Single_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bricks_Single_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Mail_Pairing" TO "anon";
GRANT ALL ON TABLE "public"."Mail_Pairing" TO "authenticated";
GRANT ALL ON TABLE "public"."Mail_Pairing" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Mail_Pairing_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Mail_Pairing_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Mail_Pairing_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Media_Adjustement" TO "anon";
GRANT ALL ON TABLE "public"."Media_Adjustement" TO "authenticated";
GRANT ALL ON TABLE "public"."Media_Adjustement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Media_Adjustement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Media_Adjustement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Media_Adjustement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Medias" TO "anon";
GRANT ALL ON TABLE "public"."Medias" TO "authenticated";
GRANT ALL ON TABLE "public"."Medias" TO "service_role";



GRANT ALL ON TABLE "public"."Node" TO "anon";
GRANT ALL ON TABLE "public"."Node" TO "authenticated";
GRANT ALL ON TABLE "public"."Node" TO "service_role";



GRANT ALL ON TABLE "public"."Platform" TO "anon";
GRANT ALL ON TABLE "public"."Platform" TO "authenticated";
GRANT ALL ON TABLE "public"."Platform" TO "service_role";



GRANT ALL ON TABLE "public"."Platform_Link" TO "anon";
GRANT ALL ON TABLE "public"."Platform_Link" TO "authenticated";
GRANT ALL ON TABLE "public"."Platform_Link" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Platform_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Platform_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Platform_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Settings" TO "anon";
GRANT ALL ON TABLE "public"."Settings" TO "authenticated";
GRANT ALL ON TABLE "public"."Settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Settings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Track" TO "anon";
GRANT ALL ON TABLE "public"."Track" TO "authenticated";
GRANT ALL ON TABLE "public"."Track" TO "service_role";



GRANT ALL ON TABLE "public"."Track_Artist" TO "anon";
GRANT ALL ON TABLE "public"."Track_Artist" TO "authenticated";
GRANT ALL ON TABLE "public"."Track_Artist" TO "service_role";



GRANT ALL ON TABLE "public"."Track_Platform_Link" TO "anon";
GRANT ALL ON TABLE "public"."Track_Platform_Link" TO "authenticated";
GRANT ALL ON TABLE "public"."Track_Platform_Link" TO "service_role";



GRANT ALL ON TABLE "public"."base_brick" TO "anon";
GRANT ALL ON TABLE "public"."base_brick" TO "authenticated";
GRANT ALL ON TABLE "public"."base_brick" TO "service_role";



GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq1" TO "service_role";



GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq2" TO "anon";
GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq2" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."base_brick_duplicate_id_seq2" TO "service_role";



GRANT ALL ON SEQUENCE "public"."base_brick_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."base_brick_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."base_brick_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
