alter type "public"."brick_type" rename to "brick_type__old_version_to_be_dropped";

create type "public"."brick_type" as enum ('HeroSection', 'Single', 'Album', 'Text', 'Platform_Link', 'Highlight', 'Audio');

create table "public"."Bricks_Audio" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone,
    "name" character varying not null,
    "media" uuid,
    "track" bigint,
    "audio" uuid
);


alter table "public"."Node" alter column type type "public"."brick_type" using type::text::"public"."brick_type";

drop type "public"."brick_type__old_version_to_be_dropped";

alter table "public"."Node" add column "Audio" bigint;

CREATE UNIQUE INDEX "Bricks_Audio_name_key" ON public."Bricks_Audio" USING btree (name);

CREATE UNIQUE INDEX "Bricks_Audio_pkey" ON public."Bricks_Audio" USING btree (id);

alter table "public"."Bricks_Audio" add constraint "Bricks_Audio_pkey" PRIMARY KEY using index "Bricks_Audio_pkey";

alter table "public"."Bricks_Audio" add constraint "Bricks_Audio_audio_fkey" FOREIGN KEY (audio) REFERENCES "Medias"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Bricks_Audio" validate constraint "Bricks_Audio_audio_fkey";

alter table "public"."Bricks_Audio" add constraint "Bricks_Audio_media_fkey" FOREIGN KEY (media) REFERENCES "Medias"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Bricks_Audio" validate constraint "Bricks_Audio_media_fkey";

alter table "public"."Bricks_Audio" add constraint "Bricks_Audio_name_key" UNIQUE using index "Bricks_Audio_name_key";

alter table "public"."Bricks_Audio" add constraint "Bricks_Audio_track_fkey" FOREIGN KEY (track) REFERENCES "Track"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Bricks_Audio" validate constraint "Bricks_Audio_track_fkey";

alter table "public"."Node" add constraint "Node_Audio_fkey" FOREIGN KEY ("Audio") REFERENCES "Bricks_Audio"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Node" validate constraint "Node_Audio_fkey";

grant delete on table "public"."Bricks_Audio" to "anon";

grant insert on table "public"."Bricks_Audio" to "anon";

grant references on table "public"."Bricks_Audio" to "anon";

grant select on table "public"."Bricks_Audio" to "anon";

grant trigger on table "public"."Bricks_Audio" to "anon";

grant truncate on table "public"."Bricks_Audio" to "anon";

grant update on table "public"."Bricks_Audio" to "anon";

grant delete on table "public"."Bricks_Audio" to "authenticated";

grant insert on table "public"."Bricks_Audio" to "authenticated";

grant references on table "public"."Bricks_Audio" to "authenticated";

grant select on table "public"."Bricks_Audio" to "authenticated";

grant trigger on table "public"."Bricks_Audio" to "authenticated";

grant truncate on table "public"."Bricks_Audio" to "authenticated";

grant update on table "public"."Bricks_Audio" to "authenticated";

grant delete on table "public"."Bricks_Audio" to "service_role";

grant insert on table "public"."Bricks_Audio" to "service_role";

grant references on table "public"."Bricks_Audio" to "service_role";

grant select on table "public"."Bricks_Audio" to "service_role";

grant trigger on table "public"."Bricks_Audio" to "service_role";

grant truncate on table "public"."Bricks_Audio" to "service_role";

grant update on table "public"."Bricks_Audio" to "service_role";


